engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: "node_modules/react-dev-config/config/eslintrc.js"
  csslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
    - "**.js"
    - "**.jsx"
    - "**.css"
    - "**.md"
